spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always

jwt:
  token:
    header: Authorization
    secret: ${JWT_SECRET}
    access-time: 3600000 # 60분
    refresh-time: 2628000000 # 한달
    issuer:  SCH